- stage: DeployProd
    displayName: 'Deploy to Production'
    dependsOn: Build
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
      - deployment: DeployProdJob
        environment: 'production'
        pool:
          vmImage: 'ubuntu-latest'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - task: AzureStaticWebApp@0
                  displayName: 'Deploy Frontend to Static Web App'
                  inputs:
                    azure_static_web_apps_api_token: $(STATIC_WEB_APP_TOKEN)
                    app_location: 'client'
                    output_location: 'dist'